server:
  port: 8081
#  ssl:
#    key-store: classpath:config/baotian.club.jks
#    key-store-password: BAOtiandi789
#    key-store-type: jks
#    key-alias: baotianclub
spring:
  thymeleaf:
    cache: false
  profiles:
    active: dev
  jpa:
    show-sql: true
  redis:
    host: 192.168.231.66
    port: 6379
    pool:
      max-idle: 8
      min-idle: 0
      max-active: 8
      max-wait: -1
    timeout: 3000
  session:
    store-type: redis
management:
  endpoints:
    web:
      exposure:
        include: '*'
  security:
    enabled: false
  #context-path: "actuator" ###配置前缀
