server:
  port: 8080
#  ssl:
#    key-store: classpath:config/baotian.club.jks
#    key-store-password: BAOtiandi789
#    key-store-type: jks
#    key-alias: baotianclub
spring:
  thymeleaf:
    cache: false
  profiles:
    active: dev
  jpa:
    show-sql: true
management:
  endpoints:
    web:
      exposure:
        include: '*'
  security:
    enabled: false
